package util

import (
	"github.com/fitstar/falcore"
	"github.com/stretchr/testify/assert"
	configutil "github.com/stuphlabs/pullcord/config/util"
	"net/http"
	"testing"
)

// TestLandingPage verifies that a Falcore RequestFilter generated by
// NewLandingFilter responds appropriately to a request. Specifically, this test
// verifies that no error occurs in the response.
func TestLandingPage(t *testing.T) {
	request, err := http.NewRequest("GET", "/", nil)
	assert.NoError(t, err)
	_, response := falcore.TestWithRequest(request, &LandingFilter{}, nil)
	assert.Equal(t, 200, response.StatusCode)
}

// TestAnotherLandingPage verifies that a Falcore RequestFilter generated by
// NewLandingFilter responds appropriately to a request for an unexpected URI.
// Specifically, this test verifies that no error occurs in the response.
func TestAnotherLandingPage(t *testing.T) {
	request, err := http.NewRequest(
		"GET",
		"/other/page/somewhere/else.php",
		nil,
	)
	assert.NoError(t, err)
	_, response := falcore.TestWithRequest(request, &LandingFilter{}, nil)
	assert.Equal(t, 200, response.StatusCode)
}

// TestPostLandingPage verifies that a Falcore RequestFilter generated by
// NewLandingFilter responds appropriately to a POST request. Specifically, this
// test verifies that no error occurs in the response.
func TestPostLandingPage(t *testing.T) {
	request, err := http.NewRequest("POST", "/", nil)
	assert.NoError(t, err)
	_, response := falcore.TestWithRequest(request, &LandingFilter{}, nil)
	assert.Equal(t, 200, response.StatusCode)
}

func TestLandingFilterFromConfig(t *testing.T) {
	test := configutil.ConfigTest{
		ResourceType: "landingfilter",
		SyntacticallyBad: []configutil.ConfigTestData{
			configutil.ConfigTestData{
				Data: "",
				Explanation: "empty config",
			},
		},
		Good: []configutil.ConfigTestData{
			configutil.ConfigTestData{
				Data: "{}",
				Explanation: "empty object",
			},
			configutil.ConfigTestData{
				Data: "null",
				Explanation: "null config",
			},
			configutil.ConfigTestData{
				Data: "42",
				Explanation: "numeric config",
			},
			configutil.ConfigTestData{
				Data: `"anything goes"`,
				Explanation: "string config",
			},
		},
	}
	test.Run(t)
}
